dist: bionic
language: cpp
scripts:
  - cmake -H. -GNinja -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd build && cmake --build .
env:
  - BUILD_TYPE=DEBUG
  - BUILD_TYPE=RELEASE
addons:
  apt:
    packages:
    - qt5-qmake
    - qtbase5-dev
    - qtdeclarative5-dev
    - libqt5charts5-dev
    - libsqlite3-dev
    - cmake
    - ninja-build